"""add embedding column

Revision ID: 1ca4eb8e0389
Revises: 4b0052b3b245
Create Date: 2026-07-01 09:16:28.990960

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca4eb8e0389'
down_revision: Union[str, Sequence[str], None] = '4b0052b3b245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', Vector(dim=1536), nullable=True))
    op.drop_column('document_chunks', 'embedding_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
