"""add sec metadata to source documents

Revision ID: 4b0052b3b245
Revises: 05fe489d3de7
Create Date: 2026-06-30 11:24:06.596140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0052b3b245'
down_revision: Union[str, Sequence[str], None] = '05fe489d3de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('ticker', sa.String(), nullable=False))
    op.add_column('source_documents', sa.Column('cik', sa.String(), nullable=False))
    op.add_column('source_documents', sa.Column('accession_number', sa.String(), nullable=False))
    op.add_column('source_documents', sa.Column('form', sa.String(), nullable=False))
    op.add_column('source_documents', sa.Column('filing_date', sa.DateTime(), nullable=False))
    op.add_column('source_documents', sa.Column('report_date', sa.DateTime(), nullable=False))
    op.add_column('source_documents', sa.Column('source_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_source_documents_accession_number'), 'source_documents', ['accession_number'], unique=True)
    op.create_index(op.f('ix_source_documents_cik'), 'source_documents', ['cik'], unique=False)
    op.create_index(op.f('ix_source_documents_filing_date'), 'source_documents', ['filing_date'], unique=False)
    op.create_index(op.f('ix_source_documents_ticker'), 'source_documents', ['ticker'], unique=False)
    op.drop_column('source_documents', 'status')
    op.drop_column('source_documents', 'total_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('source_documents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_source_documents_ticker'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_filing_date'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_cik'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_accession_number'), table_name='source_documents')
    op.drop_column('source_documents', 'source_url')
    op.drop_column('source_documents', 'report_date')
    op.drop_column('source_documents', 'filing_date')
    op.drop_column('source_documents', 'form')
    op.drop_column('source_documents', 'accession_number')
    op.drop_column('source_documents', 'cik')
    op.drop_column('source_documents', 'ticker')
    # ### end Alembic commands ###
