"""models update migrations

Revision ID: 778c1bbb01a4
Revises: f0f3fc3c3a0c
Create Date: 2026-06-29 21:49:04.275068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778c1bbb01a4'
down_revision: Union[str, Sequence[str], None] = 'f0f3fc3c3a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
